repository: 
favicon: assets/favicon.ico

# Personal info
name: Hanif Ali
title: Python Web Developer
email: alihanif016@gmail.com
phone: 
website: 

darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  hanif-ali
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: haneefaly
#linkedin_username: haneefaly
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
 - title: Quora Profile
   icon: fa-quora
   url: https://quora.com/Hanif-Ali-11

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello There! My name is Hanif. I am a Web Developer driven by passion for Programming, Mathematics and Problem Solving. I started coding when I was 14. Python and JavaScript are my languages of choice. I like to develop Web Applications, although I am exploring various other domains as well. I am also a newbie contributor to FOSS on Github.

  I am interested in Machine Learning and Cloud Computing and want to explore them further. I use Ubuntu as my full-time operating system and prefer VSCode or Vim as a text-editor. In my free time, I like to listen to Music, Write/Blog or lift some weights.

  If you are interested in hiring me for work, you can connect to me on Upwork <a href="https://www.upwork.com/o/profiles/users/~01e4e24f6f1a812341/">here</a>.

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Highly Skilled: <mark>Python</mark>  <mark>JavaScript (ES6)</mark>  <mark>Web Development</mark>  <mark>Django</mark>  <mark>Version Control (Git)</mark>  <mark>HTML/CSS</mark>  <mark>Bootstrap</mark>    <mark>Problem Solving</mark>   <mark>Interpersonal Skills </mark>

  Intermediate Knowledge: <mark>Unit Testing</mark> <mark>RESTful APIs</mark> <mark>SQL Databases</mark> <mark>Continuous Integraion</mark> <mark>Linux</mark> <mark>Shell Scripting</mark><mark>Docker</mark><mark>Performance Tuning</mark>

  Novice: <mark>Java</mark> <mark>Front-End Testing</mark> <mark>Selenium</mark>

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
